# Generated by Django 3.2.8 on 2021-10-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0002_alter_pdfile_edited_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfile',
            name='download_counter',
        ),
        migrations.RemoveField(
            model_name='pdfile',
            name='edited_file',
        ),
        migrations.RemoveField(
            model_name='pdfile',
            name='upload_time',
        ),
        migrations.RemoveField(
            model_name='pdfile',
            name='user_ip',
        ),
    ]
