# Generated by Django 3.2.8 on 2021-10-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0003_auto_20211023_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfile',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
