# Generated by Django 3.2.8 on 2021-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0004_pdfile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/images/')),
            ],
        ),
        migrations.AddField(
            model_name='pdfile',
            name='images',
            field=models.ManyToManyField(blank=True, to='pdf_editor.Images'),
        ),
    ]
